// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFjxPxQjFkz4OAx4M-GOdzuOuIf5Pm70U',
    appId: '1:488626321025:web:69a76ced7a7e42e68e7f80',
    messagingSenderId: '488626321025',
    projectId: 'sheetal-9c46f',
    authDomain: 'sheetal-9c46f.firebaseapp.com',
    storageBucket: 'sheetal-9c46f.firebasestorage.app',
    measurementId: 'G-RPB63FXLYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_xYi3dIVWMFz1EUMuccJm2DQRsL1ey6M',
    appId: '1:488626321025:android:381bb56adf9f6fa98e7f80',
    messagingSenderId: '488626321025',
    projectId: 'sheetal-9c46f',
    storageBucket: 'sheetal-9c46f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB24EsAuFEfEIUX2_Jj313MaTdK9smLqgs',
    appId: '1:488626321025:ios:89b68771672f4a658e7f80',
    messagingSenderId: '488626321025',
    projectId: 'sheetal-9c46f',
    storageBucket: 'sheetal-9c46f.firebasestorage.app',
    iosBundleId: 'com.example.sheetal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB24EsAuFEfEIUX2_Jj313MaTdK9smLqgs',
    appId: '1:488626321025:ios:89b68771672f4a658e7f80',
    messagingSenderId: '488626321025',
    projectId: 'sheetal-9c46f',
    storageBucket: 'sheetal-9c46f.firebasestorage.app',
    iosBundleId: 'com.example.sheetal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFjxPxQjFkz4OAx4M-GOdzuOuIf5Pm70U',
    appId: '1:488626321025:web:675a43a00a4b4bed8e7f80',
    messagingSenderId: '488626321025',
    projectId: 'sheetal-9c46f',
    authDomain: 'sheetal-9c46f.firebaseapp.com',
    storageBucket: 'sheetal-9c46f.firebasestorage.app',
    measurementId: 'G-DK6FRYV381',
  );

}